### ISSUE TITLE
[Step 2] 3DMM Extraction In Video ERROR

### ISSUE THREAD

**Issue by SuperMaximus1984** [vinthony/video-retalking#113]
Please help to resolve this, what can it be?

```
[Step 0] Number of frames available for inference: 1231
[Step 1] Landmarks Extraction in Video.
Downloading: "https://www.adrianbulat.com/downloads/python-fan/s3fd-619a316812.pth" to /root/                                                                                                .cache/torch/hub/checkpoints/s3fd-619a316812.pth
100%|███████████████████████████████████████████████████| 85.7M/85.7M [00:04<00:00, 19.0MB/s]
Downloading: "https://www.adrianbulat.com/downloads/python-fan/2DFAN4-cd938726ad.zip" to /roo                                                                                                t/.cache/torch/hub/checkpoints/2DFAN4-cd938726ad.zip
100%|███████████████████████████████████████████████████| 91.9M/91.9M [00:05<00:00, 19.2MB/s]
landmark Det:: 100%|█████████████████████████████████████| 1231/1231 [02:07<00:00,  9.69it/s]
[Step 2] 3DMM Extraction In Video::   0%|                           | 0/1231 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "inference.py", line 345, in <module>
    main()
  File "inference.py", line 103, in main
    trans_params, im_idx, lm_idx, _ = align_img(frame, lm_idx, lm3d_std)
  File "/workspace/video-retalking/third_part/face3d/util/preprocess.py", line 196, in align_                                                                                                img
    trans_params = np.array([w0, h0, s, t[0], t[1]])
ValueError: setting an array element with a sequence. The requested array has an inhomogeneou                                                                                                s shape after 1 dimensions. The detected shape was (5,) + inhomogeneous part.
```

**Comment by sbatururimi** [comment]
Same problem. Any help?

**Comment by sbatururimi** [comment]
Refer to https://github.com/OpenTalker/video-retalking/issues/35#issuecomment-1542944601

**Comment by zy605334918** [comment]
it's work to change this array as trans_params = np.array([w0, h0, s, t[0][0], t[1][0]])
