### ISSUE TITLE
Install Error /w requirements.txt

### ISSUE THREAD

**Issue by bbecausereasonss** [vinthony/video-retalking#15]
Followed instructions, got error

Installing collected packages: yapf, tensorboard-plugin-wit, pyasn1, ninja, lmdb, einops, dlib, addict, tensorboard-data-server, six, rsa, pyyaml, pyparsing, pyasn1-modules, protobuf, oauthlib, numpy, networkx, MarkupSafe, llvmlite, kiwisolver, importlib-resources, grpcio, future, fonttools, cycler, colorama, charset-normalizer, cachetools, absl-py, werkzeug, tqdm, tifffile, scipy, PyWavelets, python-dateutil, opencv-python, numba, markdown, kornia, imageio, google-auth, contourpy, scikit-image, resampy, requests-oauthlib, matplotlib, librosa, google-auth-oauthlib, filterpy, face-alignment, tb-nightly, facexlib, basicsr
  Running setup.py install for dlib ... error
  error: subprocess-exited-with-error

  × Running setup.py install for dlib did not run successfully.
  │ exit code: 1
  ╰─> [9 lines of output]
      running install
      C:\Users\chlyw\anaconda3\envs\video_retalking\lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_py
      running build_ext

      ERROR: CMake must be installed to build dlib

      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> dlib

**Comment by bbecausereasonss** [comment]
Fixed that, but now get this >>

(video_retalking) C:\Users\chlyw\Desktop\video-retalking>python3 inference.py --face examples/face/Carlin.mp4 --audio examples/audio/Carlin.wav --outfile results/Carlin.mp4
Traceback (most recent call last):
  File "C:\Users\chlyw\Desktop\video-retalking\inference.py", line 11, in <module>
    from third_part.face3d.extract_kp_videos import KeypointExtractor
  File "C:\Users\chlyw\Desktop\video-retalking\third_part\face3d\extract_kp_videos.py", line 6, in <module>
    import face_alignment
ModuleNotFoundError: No module named 'face_alignment'

**Comment by bbecausereasonss** [comment]
I've now tried re-installing and still get same face_alignment error.

**Comment by bbecausereasonss** [comment]
Error Log:

Successfully installed MarkupSafe-2.1.2 PyWavelets-1.4.1 colorama-0.4.6 face-alignment-1.3.5 filelock-3.10.1 imageio-2.26.1 importlib-metadata-6.1.0 jinja2-3.1.2 lazy_loader-0.2 llvmlite-0.39.1 mpmath-1.3.0 networkx-3.0 numba-0.56.4 numpy-1.23.5 opencv-python-4.7.0.72 packaging-23.0 pillow-9.4.0 scikit-image-0.20.0 scipy-1.9.1 setuptools-67.6.0 sympy-1.11.1 tifffile-2023.3.21 torch-2.0.0 tqdm-4.65.0 typing-extensions-4.5.0 zipp-3.15.0

(video_retalking) C:\Users\chlyw\Desktop\video-retalking>python3 inference.py --face examples/Carlin.mp4 --audio examples/Carlin.wav --outfile results/Carlin.mp4
Traceback (most recent call last):
  File "C:\Users\chlyw\Desktop\video-retalking\inference.py", line 11, in <module>
    from third_part.face3d.extract_kp_videos import KeypointExtractor
  File "C:\Users\chlyw\Desktop\video-retalking\third_part\face3d\extract_kp_videos.py", line 6, in <module>
    import face_alignment
ModuleNotFoundError: No module named 'face_alignment'

(video_retalking) C:\Users\chlyw\Desktop\video-retalking>python3 inference.py --face examples/video/1.mp4 --audio examples/audio/1.wav --outfile results/1.mp4
Traceback (most recent call last):
  File "C:\Users\chlyw\Desktop\video-retalking\inference.py", line 11, in <module>
    from third_part.face3d.extract_kp_videos import KeypointExtractor
  File "C:\Users\chlyw\Desktop\video-retalking\third_part\face3d\extract_kp_videos.py", line 6, in <module>
    import face_alignment
ModuleNotFoundError: No module named 'face_alignment'

(video_retalking) C:\Users\chlyw\Desktop\video-retalking>python3 inference.py --face examples/video/1.mp4 --audio examples/audio/1.wav --outfile results/1.mp4
Traceback (most recent call last):
  File "C:\Users\chlyw\Desktop\video-retalking\inference.py", line 11, in <module>
    from third_part.face3d.extract_kp_videos import KeypointExtractor
  File "C:\Users\chlyw\Desktop\video-retalking\third_part\face3d\extract_kp_videos.py", line 6, in <module>
    import face_alignment
ModuleNotFoundError: No module named 'face_alignment'

(video_retalking) C:\Users\chlyw\Desktop\video-retalking>
(video_retalking) C:\Users\chlyw\Desktop\video-retalking>pip install face-alignment
Requirement already satisfied: face-alignment in c:\users\chlyw\anaconda3\envs\video_retalking\lib\site-packages (1.3.5)
Requirement already satisfied: opencv-python in c:\users\chlyw\anaconda3\envs\video_retalking\lib\site-packages (from face-alignment) (4.7.0.72)
Requirement already satisfied: tqdm in c:\users\chlyw\anaconda3\envs\video_retalking\lib\site-packages (from face-alignment) (4.65.0)
Requirement already satisfied: numpy in c:\users\chlyw\anaconda3\envs\video_retalking\lib\site-packages (from face-alignment) (1.23.5)
Requirement already satisfied: numba in c:\users\chlyw\anaconda3\envs\video_retalking\lib\site-packages (from face-alignment) (0.56.4)
Requirement already satisfied: scikit-image in c:\users\chlyw\anaconda3\envs\video_retalking\lib\site-packages (from face-alignment) (0.20.0)
Requirement already satisfied: torch in c:\users\chlyw\anaconda3\envs\video_retalking\lib\site-packages (from face-alignment) (2.0.0)
Requirement already satisfied: scipy>=0.17 in c:\users\chlyw\anaconda3\envs\video_retalking\lib\site-packages (from face-alignment) (1.9.1)
Requirement already satisfied: llvmlite<0.40,>=0.39.0dev0 in c:\users\chlyw\anaconda3\envs\video_retalking\lib\site-packages (from numba->face-alignment) (0.39.1)
Requirement already satisfied: importlib-metadata in c:\users\chlyw\anaconda3\envs\video_retalking\lib\site-packages (from numba->face-alignment) (6.1.0)
Requirement already satisfied: setuptools in c:\users\chlyw\anaconda3\envs\video_retalking\lib\site-packages (from numba->face-alignment) (67.6.0)
Requirement already satisfied: packaging>=20.0 in c:\users\chlyw\anaconda3\envs\video_retalking\lib\site-packages (from scikit-image->face-alignment) (23.0)
Requirement already satisfied: lazy_loader>=0.1 in c:\users\chlyw\anaconda3\envs\video_retalking\lib\site-packages (from scikit-image->face-alignment) (0.2)
Requirement already satisfied: networkx>=2.8 in c:\users\chlyw\anaconda3\envs\video_retalking\lib\site-packages (from scikit-image->face-alignment) (3.0)
Requirement already satisfied: PyWavelets>=1.1.1 in c:\users\chlyw\anaconda3\envs\video_retalking\lib\site-packages (from scikit-image->face-alignment) (1.4.1)
Requirement already satisfied: pillow>=9.0.1 in c:\users\chlyw\anaconda3\envs\video_retalking\lib\site-packages (from scikit-image->face-alignment) (9.4.0)
Requirement already satisfied: tifffile>=2019.7.26 in c:\users\chlyw\anaconda3\envs\video_retalking\lib\site-packages (from scikit-image->face-alignment) (2023.3.21)
Requirement already satisfied: imageio>=2.4.1 in c:\users\chlyw\anaconda3\envs\video_retalking\lib\site-packages (from scikit-image->face-alignment) (2.26.1)
Requirement already satisfied: sympy in c:\users\chlyw\anaconda3\envs\video_retalking\lib\site-packages (from torch->face-alignment) (1.11.1)
Requirement already satisfied: jinja2 in c:\users\chlyw\anaconda3\envs\video_retalking\lib\site-packages (from torch->face-alignment) (3.1.2)
Requirement already satisfied: filelock in c:\users\chlyw\anaconda3\envs\video_retalking\lib\site-packages (from torch->face-alignment) (3.10.1)
Requirement already satisfied: typing-extensions in c:\users\chlyw\anaconda3\envs\video_retalking\lib\site-packages (from torch->face-alignment) (4.5.0)
Requirement already satisfied: colorama in c:\users\chlyw\anaconda3\envs\video_retalking\lib\site-packages (from tqdm->face-alignment) (0.4.6)
Requirement already satisfied: zipp>=0.5 in c:\users\chlyw\anaconda3\envs\video_retalking\lib\site-packages (from importlib-metadata->numba->face-alignment) (3.15.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\chlyw\anaconda3\envs\video_retalking\lib\site-packages (from jinja2->torch->face-alignment) (2.1.2)
Requirement already satisfied: mpmath>=0.19 in c:\users\chlyw\anaconda3\envs\video_retalking\lib\site-packages (from sympy->torch->face-alignment) (1.3.0)

(video_retalking) C:\Users\chlyw\Desktop\video-retalking>python3 inference.py --face examples/video/1.mp4 --audio examples/audio/1.wav --outfile results/1.mp4
Traceback (most recent call last):
  File "C:\Users\chlyw\Desktop\video-retalking\inference.py", line 11, in <module>
    from third_part.face3d.extract_kp_videos import KeypointExtractor
  File "C:\Users\chlyw\Desktop\video-retalking\third_part\face3d\extract_kp_videos.py", line 6, in <module>
    import face_alignment
ModuleNotFoundError: No module named 'face_alignment'

**Comment by bbecausereasonss** [comment]
FIXED. Bunch of issues. Had to launch using python not python3, had to uninstall and reinstall Torch /w Cuda.

**Comment by byixi2023** [comment]
> Fixed that, but now get this >>
> 
> (video_retalking) C:\Users\chlyw\Desktop\video-retalking>python3 inference.py --face examples/face/Carlin.mp4 --audio examples/audio/Carlin.wav --outfile results/Carlin.mp4 Traceback (most recent call last): File "C:\Users\chlyw\Desktop\video-retalking\inference.py", line 11, in from third_part.face3d.extract_kp_videos import KeypointExtractor File "C:\Users\chlyw\Desktop\video-retalking\third_part\face3d\extract_kp_videos.py", line 6, in import face_alignment ModuleNotFoundError: No module named 'face_alignment'

@bbecausereasonss could you tell me how you fix this question?
