### ISSUE TITLE
Error on the replicate.com

### ISSUE THREAD

**Issue by xGhostOfSparta** [vinthony/video-retalking#170]
traying the demo on https://replicate.com/cjwbw/video-retalking
getting this error every time 

`Traceback (most recent call last):
File "/root/.pyenv/versions/3.11.6/lib/python3.11/site-packages/cog/server/worker.py", line 217, in _predict
result = predict(**payload)
^^^^^^^^^^^^^^^^^^
File "/src/predict.py", line 309, in predict
pred, _, _ = self.enhancer.process(
^^^^^^^^^^^^^^^^^^^^^^
File "/src/third_part/GPEN/gpen_face_enhancer.py", line 113, in process
mask_sharp = cv2.GaussianBlur(mask_sharp, (0,0), sigmaX=1, sigmaY=1, borderType = cv2.BORDER_DEFAULT)
^^^^^^^^^^
UnboundLocalError: cannot access local variable 'mask_sharp' where it is not associated with a value`

**Comment by nikolaigeorgie** [comment]
> traying the demo on https://replicate.com/cjwbw/video-retalking getting this error every time
> 
> `Traceback (most recent call last): File "/root/.pyenv/versions/3.11.6/lib/python3.11/site-packages/cog/server/worker.py", line 217, in _predict result = predict(**payload) ^^^^^^^^^^^^^^^^^^ File "/src/predict.py", line 309, in predict pred, _, _ = self.enhancer.process( ^^^^^^^^^^^^^^^^^^^^^^ File "/src/third_part/GPEN/gpen_face_enhancer.py", line 113, in process mask_sharp = cv2.GaussianBlur(mask_sharp, (0,0), sigmaX=1, sigmaY=1, borderType = cv2.BORDER_DEFAULT) ^^^^^^^^^^ UnboundLocalError: cannot access local variable 'mask_sharp' where it is not associated with a value`

duplicate #190
