### ISSUE TITLE
UnboundLocalError: local variable 'mask_sharp' referenced before assignment

### ISSUE THREAD

**Issue by Kaszanas** [vinthony/video-retalking#176]
When running the code it is unfortunately not using GPU, and fails at this stage.

```
landmark Det::   0%|                                                                                        | 0/332 [00:00<?, ?it/s]No face detected in this image
landmark Det:: 100%|██████████████████████████████████████████████████████████████████████████████| 332/332 [01:42<00:00,  3.24it/s][Step 2] 3DMM Extraction In Video:: 100%|█████████████████████████████████████████████████████████| 332/332 [00:19<00:00, 17.31it/s]using expression center
Load checkpoint from: checkpoints/DNet.pt
Load checkpoint from: checkpoints/LNet.pth
Load checkpoint from: checkpoints/ENet.pth
[Step 3] Stabilize the expression In Video:: 100%|████████████████████████████████████████████████| 332/332 [02:16<00:00,  2.43it/s][Step 4] Load audio; Length of mel chunks: 611
[Step 5] Reference Enhancement:   0%|                                                                       | 0/332 [00:00<?, ?it/s]Traceback (most recent call last):
  File "inference.py", line 345, in <module>
    main()
  File "inference.py", line 201, in main
    pred, _, _ = enhancer.process(img, img, face_enhance=True, possion_blending=False)
  File "/app/video-retalking/third_part/GPEN/gpen_face_enhancer.py", line 113, in process
    mask_sharp = cv2.GaussianBlur(mask_sharp, (0,0), sigmaX=1, sigmaY=1, borderType = cv2.BORDER_DEFAULT)
UnboundLocalError: local variable 'mask_sharp' referenced before assignment
```

Providing a dockerfile would also be beneficial.

**Comment by mertuner** [comment]
I get this error anytime I try it with a video in portrait mode. However, never encountered with a video in a landscape mode.

**Comment by zxc67373** [comment]
The video did not detect a face, so it reported an error
