### ISSUE TITLE
Traceback error

### ISSUE THREAD

**Issue by mavashis4toshi** [vinthony/video-retalking#177]
Traceback (most recent call last):
  File "/kaggle/working/video-retalking/inference.py", line 345, in <module>
    main()
  File "/kaggle/working/video-retalking/inference.py", line 103, in main
    trans_params, im_idx, lm_idx, _ = align_img(frame, lm_idx, lm3d_std)
  File "/kaggle/working/video-retalking/third_part/face3d/util/preprocess.py", line 196, in align_img
    trans_params = np.array([w0, h0, s, t[0], t[1]])
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (5,) + inhomogeneous part.

**Comment by Player-ghq** [comment]
could you solve? I have the same issue......
