### ISSUE TITLE
mask_sharp error

### ISSUE THREAD

**Issue by zwvipline** [vinthony/video-retalking#190]
Traceback (most recent call last):
  File "D:\AI\video-retalking\inference.py", line 345, in <module>
    main()
  File "D:\AI\video-retalking\inference.py", line 201, in main
    pred, _, _ = enhancer.process(img, img, face_enhance=True, possion_blending=False)
  File "D:\AI\video-retalking\third_part\GPEN\gpen_face_enhancer.py", line 113, in process
    mask_sharp = cv2.GaussianBlur(mask_sharp, (0,0), sigmaX=1, sigmaY=1, borderType = cv2.BORDER_DEFAULT)
UnboundLocalError: local variable 'mask_sharp' referenced before assignment

**Comment by tongtrongnhan** [comment]
I have same issue too. After 30 min test I fixed it. You can consider my solution:

- Check video file on the face model <= the face of the model in video must display 100% on all frame. <= you can cut the frame on video which not exist model face and try again ;)

**Comment by zzqwdwd** [comment]
> I have same issue too. After 30 min test I fixed it. You can consider my solution:
> 
> * Check video file on the face model <= the face of the model in video must display 100% on all frame. <= you can cut the frame on video which not exist model face and try again ;)

Could you please explain in detail how it was done
