### ISSUE TITLE
ImportError: dlopen(/opt/anaconda3/envs/video_retalking/lib/python3.8/site-packages/_dlib_pybind11.cpython-38-darwin.so, 0x0002): symbol not found in flat namespace (_png_do_expand_palette_rgb8_neon)

### ISSUE THREAD

**Issue by shaqixiaobao** [vinthony/video-retalking#191]
**the log:**
(video_retalking)  video-retalking % python3 inference.py \       
  --face examples/face/1.mp4 \
  --audio examples/audio/2.wav \
  --outfile results/1_1.mp4
/opt/anaconda3/envs/video_retalking/lib/python3.8/site-packages/torchvision/transforms/functional_tensor.py:5: UserWarning: The torchvision.transforms.functional_tensor module is deprecated in 0.15 and will be **removed in 0.17**. Please don't rely on it. You probably just need to use APIs in torchvision.transforms.functional or in torchvision.transforms.v2.functional.
  warnings.warn(
Traceback (most recent call last):
  File "inference.py", line 22, in <module>
    from utils.ffhq_preprocess import Croper
  File "/Users/weicong/video-retalking/utils/ffhq_preprocess.py", line 31, in <module>
    import dlib
  File "/opt/anaconda3/envs/video_retalking/lib/python3.8/site-packages/dlib/__init__.py", line 19, in <module>
    from _dlib_pybind11 import *
ImportError: dlopen(/opt/anaconda3/envs/video_retalking/lib/python3.8/site-packages/_dlib_pybind11.cpython-38-darwin.so, 0x0002): symbol not found in flat namespace (_png_do_expand_palette_rgb8_neon)

**the quesiton:I encountered this error during runtime. May I ask if there is a missing reference to any package？**

**Comment by ashwani-ver** [comment]
> **the log:** (video_retalking) video-retalking % python3 inference.py \ --face examples/face/1.mp4 --audio examples/audio/2.wav --outfile results/1_1.mp4 /opt/anaconda3/envs/video_retalking/lib/python3.8/site-packages/torchvision/transforms/functional_tensor.py:5: UserWarning: The torchvision.transforms.functional_tensor module is deprecated in 0.15 and will be **removed in 0.17**. Please don't rely on it. You probably just need to use APIs in torchvision.transforms.functional or in torchvision.transforms.v2.functional. warnings.warn( Traceback (most recent call last): File "inference.py", line 22, in from utils.ffhq_preprocess import Croper File "/Users/weicong/video-retalking/utils/ffhq_preprocess.py", line 31, in import dlib File "/opt/anaconda3/envs/video_retalking/lib/python3.8/site-packages/dlib/**init**.py", line 19, in from _dlib_pybind11 import * ImportError: dlopen(/opt/anaconda3/envs/video_retalking/lib/python3.8/site-packages/_dlib_pybind11.cpython-38-darwin.so, 0x0002): symbol not found in flat namespace (_png_do_expand_palette_rgb8_neon)
> 
> **the quesiton:I encountered this error during runtime. May I ask if there is a missing reference to any package？**

instead of python version 3.8 use 3.10.12 for creating environment. for me the problem was solved
