### ISSUE TITLE
No such file or directory 2DFAN4-cd938726ad.zip

### ISSUE THREAD

**Issue by ZAKALKA** [vinthony/video-retalking#195]
Can't run inference.py almost immediately issue with 2DFAN4-cd938726ad.zip pops up. It says it can't find it, but when I copy and paste it separately - it finds it, when I locate it manualy -it finds it, when I reinstall it manually - I find it. But no matter what I do, including changing permissions, path in variables, or even trying to modify cog.yaml where the path to 2DFAN4 is listed - nothing helps at all. Could you please help me with this one?

![2d 1](https://github.com/OpenTalker/video-retalking/assets/156037092/8d191ac5-12dc-4a77-b1dd-befb9a5522fd)
![2d 2](https://github.com/OpenTalker/video-retalking/assets/156037092/c0260e49-6218-4114-aa29-b2b5c71315c6)

Here is the traceback from the code itself:

(base) C:\AI\video-retalking>python inference.py --face examples/face/reporter.mp4 --audio examples/audio/sound.mp3 --outfile results/reporterretalkingapp.mp4
C:\AI\conda\Lib\site-packages\paramiko\transport.py:219: CryptographyDeprecationWarning: Blowfish has been deprecated
  "class": algorithms.Blowfish,
C:\AI\conda\Lib\site-packages\torchvision\transforms\functional_tensor.py:5: UserWarning: The torchvision.transforms.functional_tensor module is deprecated in 0.15 and will be **removed in 0.17**. Please don't rely on it. You probably just need to use APIs in torchvision.transforms.functional or in torchvision.transforms.v2.functional.
  warnings.warn(
[Info] Using cuda for inference.
[Step 0] Number of frames available for inference: 519
[Step 1] Landmarks Extraction in Video.
Traceback (most recent call last):
  File "C:\AI\video-retalking\inference.py", line 345, in <module>
    main()
  File "C:\AI\video-retalking\inference.py", line 81, in main
    kp_extractor = KeypointExtractor()
                   ^^^^^^^^^^^^^^^^^^^
  File "C:\AI\video-retalking\third_part\face3d\extract_kp_videos.py", line 18, in __init__
    self.detector = face_alignment.FaceAlignment(face_alignment.LandmarksType.TWO_D, device=device)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI\conda\Lib\site-packages\face_alignment\api.py", line 87, in __init__
    self.face_alignment_net = torch.jit.load(
                              ^^^^^^^^^^^^^^^
  File "C:\AI\conda\Lib\site-packages\torch\jit\_serialization.py", line 162, in load
    cpp_module = torch._C.import_ir_module(cu, str(f), map_location, _extra_files, _restore_shapes)  # type: ignore[call-arg]
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: open file failed because of errno 2 on fopen: No such file or directory, file path: C:\Users\Андрей/.cache\torch\hub\checkpoints\2DFAN4-cd938726ad.zip

**Comment by JiliHili** [comment]
your username shouldnt has speacial character
add these to inference.py
import os
os.environ['TORCH_HOME']='C:/Data/torch'
