### ISSUE TITLE
Error in the fifth step of the program: (GPEN)

### ISSUE THREAD

**Issue by labels168** [vinthony/video-retalking#20]
Traceback (most recent call last):
  File "inference.py", line 342, in <module>
    main()
  File "inference.py", line 198, in main
    pred, _, _ = enhancer.process(img, img, face_enhance=True, possion_blending=False)
  File "C:\AI-3\third_part\GPEN\gpen_face_enhancer.py", line 116, in process
    mask_sharp = cv2.GaussianBlur(mask_sharp, (0,0), sigmaX=1, sigmaY=1, borderType = cv2.BORDER_DEFAULT)
UnboundLocalError: local variable 'mask_sharp' referenced before assignment
=====================================================
Looking for any help and answers, thank you teachers and designers.

**Comment by kunncheng** [comment]
Its' similar to [this issue](https://github.com/vinthony/video-retalking/issues/14).

Hope this helps~

**Comment by labels168** [comment]
> 它與[this issue](https://github.com/vinthony/video-retalking/issues/14)類似。
> 
> 希望這有幫助~

Ok, thanks for the guide!
