### ISSUE TITLE
ModuleNotFoundError: No module named 'face_alignment'

### ISSUE THREAD

**Issue by frnk-cnt** [vinthony/video-retalking#207]
Getting this error when running the inferrence
video_retalking) C:\Users\f\ai\video-retalking>python3 inference.py --face examples/face/3.mp4 --audio examples/audio/2.wav --outfile results/3_2.mp4
Traceback (most recent call last):
  File "C:\Users\f\ai\video-retalking\inference.py", line 14, in <module>
    from third_part.face3d.extract_kp_videos import KeypointExtractor
  File "C:\Users\f\ai\video-retalking\third_part\face3d\extract_kp_videos.py", line 6, in <module>
    import face_alignment
ModuleNotFoundError: No module named 'face_alignment'

**Comment by 158code** [comment]
pip install - requirments.txt

**Comment by JJayasri** [comment]
run--> pip install face_alignment
