### ISSUE TITLE
SSL Issue with usage

### ISSUE THREAD

**Issue by gamesjarland** [vinthony/video-retalking#212]
Hi there, 
I'm having an issue where the SSL certificate verification is failing

`(videoretalking) D:\video-retalking>python inference.py --face examples/face/1.mp4 --audio examples/audio/1.wav --outfile results/1_1.mp4
[Info] Using cuda for inference.
[Step 0] Number of frames available for inference: 135
[Step 1] Landmarks Extraction in Video.
Downloading: "https://www.adrianbulat.com/downloads/python-fan/2DFAN4-cd938726ad.zip" to C:\Users\evada/.cache\torch\hub\checkpoints\2DFAN4-cd938726ad.zip
Traceback (most recent call last):
  File "D:\miniconda3\envs\videoretalking\lib\urllib\request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "D:\miniconda3\envs\videoretalking\lib\http\client.py", line 1285, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "D:\miniconda3\envs\videoretalking\lib\http\client.py", line 1331, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "D:\miniconda3\envs\videoretalking\lib\http\client.py", line 1280, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "D:\miniconda3\envs\videoretalking\lib\http\client.py", line 1040, in _send_output
    self.send(msg)
  File "D:\miniconda3\envs\videoretalking\lib\http\client.py", line 980, in send
    self.connect()
  File "D:\miniconda3\envs\videoretalking\lib\http\client.py", line 1454, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "D:\miniconda3\envs\videoretalking\lib\ssl.py", line 501, in wrap_socket
    return self.sslsocket_class._create(
  File "D:\miniconda3\envs\videoretalking\lib\ssl.py", line 1074, in _create
    self.do_handshake()
  File "D:\miniconda3\envs\videoretalking\lib\ssl.py", line 1343, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\video-retalking\inference.py", line 345, in <module>
    main()
  File "D:\video-retalking\inference.py", line 81, in main
    kp_extractor = KeypointExtractor()
  File "D:\video-retalking\third_part\face3d\extract_kp_videos.py", line 18, in __init__
    self.detector = face_alignment.FaceAlignment(face_alignment.LandmarksType._2D, device=device)
  File "D:\miniconda3\envs\videoretalking\lib\site-packages\face_alignment\api.py", line 85, in __init__
    load_file_from_url(models_urls.get(pytorch_version, default_model_urls)[network_name]))
  File "D:\miniconda3\envs\videoretalking\lib\site-packages\face_alignment\utils.py", line 375, in load_file_from_url
    download_url_to_file(url, cached_file, hash_prefix, progress=progress)
  File "D:\miniconda3\envs\videoretalking\lib\site-packages\torch\hub.py", line 419, in download_url_to_file
    u = urlopen(req)
  File "D:\miniconda3\envs\videoretalking\lib\urllib\request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "D:\miniconda3\envs\videoretalking\lib\urllib\request.py", line 519, in open
    response = self._open(req, data)
  File "D:\miniconda3\envs\videoretalking\lib\urllib\request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "D:\miniconda3\envs\videoretalking\lib\urllib\request.py", line 496, in _call_chain
    result = func(*args)
  File "D:\miniconda3\envs\videoretalking\lib\urllib\request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "D:\miniconda3\envs\videoretalking\lib\urllib\request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)>
`

I have installed Certifi and I can confirm that the Trusted Root is installing, but cannot seem to get past this issue.

**Comment by gamesjarland** [comment]
![image](https://github.com/OpenTalker/video-retalking/assets/102849765/bb4808ea-07cb-4de5-ade1-eb5fdb91c9bd)

**Comment by 158code** [comment]
same issue
