### ISSUE TITLE
UnboundLocalError: local variable 'keypoints' referenced before assignment

### ISSUE THREAD

**Issue by hiowenluke** [vinthony/video-retalking#222]
```
Traceback (most recent call last):
  File "inference.py", line 345, in <module>
    main()
  File "inference.py", line 82, in main
    lm = kp_extractor.extract_keypoint(frames_pil, './temp/'+base_name+'_landmarks.txt')
  File "D:\video-retalking\third_part\face3d\extract_kp_videos.py", line 29, in extract_keypoint
    current_kp = self.extract_keypoint(image)
  File "D:\video-retalking\third_part\face3d\extract_kp_videos.py", line 57, in extract_keypoint
    return keypoints
UnboundLocalError: local variable 'keypoints' referenced before assignment
```

OS: Windows 10

**Comment by MehmetSaitAlpaydin** [comment]
I am having the same issue.

**Comment by RASPIAUDIO** [comment]
same same

**Comment by vettorazi** [comment]
same here

**Comment by zergzzlun** [comment]
If you check the error info again there's a good chance you'll find more error information above. The error message you posted is most likely caused by [Line 41 of the same file](https://github.com/OpenTalker/video-retalking/blob/main/third_part/face3d/extract_kp_videos.py#L41).
I'm guessing it's caused by CUDA version conflict in PyTorch.

**Comment by dadede999** [comment]
use this，it work
git clone https://github.com/vinthony/video-retalking.git 
cd video-retalking 
conda create -n video_retalking python=3.10 
conda activate video_retalking 
pip install torch==2.0.0+cu118 torchvision==0.15.1+cu118 torchaudio==2.0.1 --index-url https://download.pytorch.org/whl/cu118
