### ISSUE TITLE
ImportError: cannot import name 'packaging' from 'pkg_resources'

### ISSUE THREAD

**Issue by anastalaz** [vinthony/video-retalking#244]
Trying to run inference.py I get following error:

Traceback (most recent call last):
  File "inference.py", line 16, in <module>
    from third_part.GPEN.gpen_face_enhancer import FaceEnhancement
  File "/home/anastalaz/dev/video-retalking/third_part/GPEN/gpen_face_enhancer.py", line 8, in <module>
    from face_model.face_gan import FaceGAN
  File "/home/anastalaz/dev/video-retalking/third_part/GPEN/face_model/face_gan.py", line 13, in <module>
    from face_model.gpen_model import FullGenerator
  File "/home/anastalaz/dev/video-retalking/third_part/GPEN/face_model/gpen_model.py", line 16, in <module>
    from face_model.op import FusedLeakyReLU, fused_leaky_relu, upfirdn2d
  File "/home/anastalaz/dev/video-retalking/third_part/GPEN/face_model/op/__init__.py", line 1, in <module>
    from .fused_act import FusedLeakyReLU, fused_leaky_relu
  File "/home/anastalaz/dev/video-retalking/third_part/GPEN/face_model/op/fused_act.py", line 8, in <module>
    from torch.utils.cpp_extension import load, _import_module_from_library
  File "/home/anastalaz/miniconda3/envs/video_retalking/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 23, in <module>
    from pkg_resources import packaging  # type: ignore[attr-defined]
ImportError: cannot import name 'packaging' from 'pkg_resources'

Anyone knows what to do?

**Comment by tom20180101** [comment]
try  uninstall setuptools and  install setuptools==69.5.1

**Comment by ashwani-ver** [comment]
> try uninstall setuptools and install setuptools==69.5.1

Hey,
I installed the version you told. but i am facing one issue.
After I hit the inference command, nothing is coming, it is stuck at that point. command is not executing and also not throwing any error.
How can i solve this?
thank you

**Comment by ashwani-ver** [comment]
I solved the problem with 2 steps. 
1.Go to file /usr/local/lib/python3.10/dist-packages/basicsr/data/degradations.py and change line number 8 to:

from torchvision.transforms.functional import rgb_to_grayscale
Got the solution from https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/13985

2. use python version 3.10.12 for creating environment instead of 3.8. For me it worked.

**Comment by tom20180101** [comment]
> I solved the problem with 2 steps. 1.Go to file /usr/local/lib/python3.10/dist-packages/basicsr/data/degradations.py and change line number 8 to:
> 
> from torchvision.transforms.functional import rgb_to_grayscale Got the solution from [AUTOMATIC1111/stable-diffusion-webui#13985](https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/13985)
> 
> 2. use python version 3.10.12 for creating environment instead of 3.8. For me it worked.

in my server ,i use python 3.8 ,uninstall setuptools and install setuptools==69.5.1 ,then it worked. :)
