### ISSUE TITLE
New to tis but have an error stopping me can anyone hhelp?

### ISSUE THREAD

**Issue by AiBJt** [vinthony/video-retalking#249]
[Info] Using cuda for inference.
[Step 0] Number of frames available for inference: 822
[Step 1] Using saved landmarks.
[Step 2] 3DMM Extraction In Video:: 100%|████████████████████████████████████████████| 822/822 [00:08<00:00, 97.96it/s]
using expression center
Load checkpoint from: checkpoints/DNet.pt
Load checkpoint from: checkpoints/LNet.pth
Load checkpoint from: checkpoints/ENet.pth
[Step 3] Using saved stablized video.
[Step 4] Load audio; Length of mel chunks: 819
[Step 5] Reference Enhancement:  14%|██████▋                                         | 114/819 [00:37<03:49,  3.07it/s]
Traceback (most recent call last):
  File "C:\Users\black\Downloads\video-retalking-main\venv\lib\site-packages\gradio\queueing.py", line 407, in call_prediction
    output = await route_utils.call_process_api(
  File "C:\Users\black\Downloads\video-retalking-main\venv\lib\site-packages\gradio\route_utils.py", line 226, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\Users\black\Downloads\video-retalking-main\venv\lib\site-packages\gradio\blocks.py", line 1550, in process_api
    result = await self.call_function(
  File "C:\Users\black\Downloads\video-retalking-main\venv\lib\site-packages\gradio\blocks.py", line 1185, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\black\Downloads\video-retalking-main\venv\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "C:\Users\black\Downloads\video-retalking-main\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
  File "C:\Users\black\Downloads\video-retalking-main\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 859, in run
    result = context.run(func, *args)
  File "C:\Users\black\Downloads\video-retalking-main\venv\lib\site-packages\gradio\utils.py", line 661, in wrapper
    response = f(*args, **kwargs)
  File "C:\Users\black\Downloads\video-retalking-main\webUI.py", line 383, in inference
    pred, _, _ = enhancer.process(img, img, face_enhance=True, possion_blending=False)
  File "C:\Users\black\Downloads\video-retalking-main\third_part\GPEN\gpen_face_enhancer.py", line 113, in process
    mask_sharp = cv2.GaussianBlur(mask_sharp, (0,0), sigmaX=1, sigmaY=1, borderType = cv2.BORDER_DEFAULT)
UnboundLocalError: local variable 'mask_sharp' referenced before assignment

I have absolutely no idea what i have done wrong, It was supposed to be a standalone download that required nothing but running of a bat file, anyway thanks for any help!

**Comment by AiBJt** [comment]
Im on windows 10 let me know if you need any other info.
