### ISSUE TITLE
Different Errors while trying to install

### ISSUE THREAD

**Issue by AlonDan** [vinthony/video-retalking#25]
I followed the instructions on the main page,
to make my first test simple I put the audio and wav in the root directory to make a short path:

`python3 inference.py --face 1.mp4 --audio 1.wav --outfile 1_1.mp4`

After installing the cuda and requirements as explained, 
I had a lot of different errors of missing modules so tried to install them by myself
But the last error I'm stuck on I can't get rid of:

```
D:\Video_Retalking>python3 inference.py --face 1.mp4 --audio 1.wav --outfile 1_1.mp4
No CUDA runtime is found, using CUDA_HOME='C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3'
C:\Users\Alon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\torchvision\transforms\functional_tensor.py:5: UserWarning: The torchvision.transforms.functional_tensor module is deprecated in 0.15 and will be **removed in 0.17**. Please don't rely on it. You probably just need to use APIs in torchvision.transforms.functional or in torchvision.transforms.v2.functional.
  warnings.warn(
Traceback (most recent call last):
  File "D:\Video_Retalking\inference.py", line 19, in <module>
    from utils.ffhq_preprocess import Croper
  File "D:\Video_Retalking\utils\ffhq_preprocess.py", line 31, in <module>
    import dlib
  File "C:\Users\Alon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\dlib\__init__.py", line 19, in <module>
    from _dlib_pybind11 import *
ImportError: DLL load failed while importing _dlib_pybind11: The specified module could not be found.

```
---

I tried pip install it, pip3 install and even conda install but nothing solve the problem.
I also tried to re-install CUDA but I still get the same error as above.

Any idea how to fix that and make Video-Retalking run local on Anaconda?
Thanks ahead 🙏

**Comment by kunncheng** [comment]
I googled some links.   
https://github.com/davisking/dlib/issues/2097
https://stackoverflow.com/questions/62255730/dlib-importerror-in-windows-10-on-line-dlib-pybind11-import-dll-load-failed

Hope that helps~

**Comment by wei-kris** [comment]
I have the same error🙋‍  I used Windows 10.

**Comment by Titukas22** [comment]
try python 3.7
