### ISSUE TITLE
windows 11 

### ISSUE THREAD

**Issue by hjj-lmx** [vinthony/video-retalking#259]
Unable to load GFPGANv1.3.pth

Traceback (most recent call last):
  File "E:\video-retalking\inference.py", line 345, in <module>
    main()
  File "E:\video-retalking\inference.py", line 39, in main
    restorer = GFPGANer(model_path='checkpoints/GFPGANv1.3.pth', upscale=1, arch='clean', channel_multiplier=2, bg_upsampler=None)
  File "E:\video-retalking\third_part\GFPGAN\gfpgan\utils.py", line 76, in __init__
    self.face_helper = FaceRestoreHelper(
  File "D:\Program Files\miniconda3\envs\video_retalking\lib\site-packages\facexlib\utils\face_restoration_helper.py", line 99, in __init__
    self.face_det = init_detection_model(det_model, half=False, device=self.device, model_rootpath=model_rootpath)
  File "D:\Program Files\miniconda3\envs\video_retalking\lib\site-packages\facexlib\detection\__init__.py", line 22, in init_detection_model
    load_net = torch.load(model_path, map_location=lambda storage, loc: storage)
  File "D:\Program Files\miniconda3\envs\video_retalking\lib\site-packages\torch\serialization.py", line 815, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "D:\Program Files\miniconda3\envs\video_retalking\lib\site-packages\torch\serialization.py", line 1051, in _legacy_load
    typed_storage._untyped_storage._set_from_file(
RuntimeError: unexpected EOF, expected 724613 more bytes. The file might be corrupted.

**Comment by a907066892** [comment]
我也有这个问题

**Comment by envious** [comment]
same issue, has anyone managed to resolve this?
