### ISSUE TITLE
Installation problem: numpy version is missing VisibleDeprecationWarning

### ISSUE THREAD

**Issue by iv2985** [vinthony/video-retalking#274]
I had lots of problems before with the default instructions for library and package version conflicts, but from reading other open issues, I found the package installation order below does not have package manager errors. I am using the slightly newer torch versions with python 3.10:
```
conda config --add channels conda-forge
conda config --add channels nvidia
conda config --add channels pytorch
conda install cmake==3.25.2 -y
export CC=gcc
export GXX=g++
pip install -r requirements.txt
pip3 uninstall torch torchvision torchaudio -y
conda install pytorch==1.13.1 torchvision==0.14.1 torchaudio==0.13.1 pytorch-cuda=11.7
chmod u+x inference_videoretalking.sh # prepare to run it
```

However, it seems the numpy version somehow doesn't work with part of the pipeline. **_Any advice?_**
```
$ ./inference_videoretalking.sh                                     
Traceback (most recent call last):                                                                                                                      
  File "/home/imv/code/msm/retalker/retalker/inference.py", line 12, in <module>                                                                        
    from third_part.face3d.util.preprocess import align_img                                                                                             
  File "/home/imv/code/msm/retalker/retalker/third_part/face3d/util/preprocess.py", line 13, in <module>                                                
    warnings.filterwarnings("ignore", category=np.VisibleDeprecationWarning)                                                                            
  File "/home/imv/miniconda3/envs/retalker/lib/python3.10/site-packages/numpy/__init__.py", line 414, in __getattr__                                    
    raise AttributeError("module {!r} has no attribute "                                                                                                
AttributeError: module 'numpy' has no attribute 'VisibleDeprecationWarning'        
```

Python version
```
(retalker) imv@srv-10g:~/code/msm/retalker/retalker$ python --version
Python 3.10.15
```

Here are my installed conda and pip package versions:
```
(retalker) imv@srv-10g:~/code/msm/retalker/retalker$ conda list | grep numpy                                                                            
numpy                     1.23.4                   pypi_0    pypi                                                                                       
(retalker) imv@srv-10g:~/code/msm/retalker/retalker$ conda list                                                                                         
# packages in environment at /home/imv/miniconda3/envs/retalker:                                                                                        
#                                                                                                                                                       
# Name                    Version                   Build  Channel                                                                                      
_libgcc_mutex             0.1                 conda_forge    conda-forge                                                                                
_openmp_mutex             4.5                       2_gnu    conda-forge
absl-py                   2.1.0                    pypi_0    pypi
addict                    2.4.0                    pypi_0    pypi
aiofiles                  23.2.1                   pypi_0    pypi
annotated-types           0.7.0                    pypi_0    pypi
anyio                     4.6.0                    pypi_0    pypi
audioread                 3.0.1                    pypi_0    pypi
basicsr                   1.4.2                    pypi_0    pypi
blas                      1.0                         mkl    conda-forge
brotli-python             1.1.0           py310hf71b8c6_2    conda-forge
bzip2                     1.0.8                h5eee18b_6  
c-ares                    1.33.1               heb4867d_0    conda-forge
ca-certificates           2024.9.24            h06a4308_0  
certifi                   2024.8.30          pyhd8ed1ab_0    conda-forge
cffi                      1.17.1          py310h8deb56e_0    conda-forge
charset-normalizer        3.4.0              pyhd8ed1ab_0    conda-forge
click                     8.1.7                    pypi_0    pypi
cmake                     3.25.2               h077f3f9_0    conda-forge
contourpy                 1.3.0                    pypi_0    pypi
cuda-cudart               11.7.99                       0    nvidia
cuda-cupti                11.7.101                      0    nvidia
cuda-libraries            11.7.1                        0    nvidia
cuda-nvrtc                11.7.99                       0    nvidia
cuda-nvtx                 11.7.91                       0    nvidia
cuda-runtime              11.7.1                        0    nvidia
cuda-version              12.6                          3    nvidia
cycler                    0.12.1                   pypi_0    pypi
decorator                 5.1.1                    pypi_0    pypi
dlib                      19.24.0                  pypi_0    pypi
einops                    0.4.1                    pypi_0    pypi
exceptiongroup            1.2.2                    pypi_0    pypi
expat                     2.6.3                h5888daf_0    conda-forge
face-alignment            1.3.4                    pypi_0    pypi
facexlib                  0.2.5                    pypi_0    pypi
fastapi                   0.115.0                  pypi_0    pypi
ffmpeg                    4.3                  hf484d3e_0    pytorch
ffmpy                     0.4.0                    pypi_0    pypi
filelock                  3.16.1                   pypi_0    pypi
filterpy                  1.4.5                    pypi_0    pypi
fonttools                 4.54.1                   pypi_0    pypi
freetype                  2.12.1               h267a509_2    conda-forge
fsspec                    2024.9.0                 pypi_0    pypi
future                    1.0.0                    pypi_0    pypi
gmp                       6.3.0                hac33072_2    conda-forge
gnutls                    3.6.13               h85f3911_1    conda-forge
gradio                    5.0.0                    pypi_0    pypi
gradio-client             1.4.0                    pypi_0    pypi
grpcio                    1.66.2                   pypi_0    pypi
h11                       0.14.0                   pypi_0    pypi
h2                        4.1.0              pyhd8ed1ab_0    conda-forge
hpack                     4.0.0              pyh9f0ad1d_0    conda-forge
httpcore                  1.0.6                    pypi_0    pypi
httpx                     0.27.2                   pypi_0    pypi
huggingface-hub           0.25.2                   pypi_0    pypi
hyperframe                6.0.1              pyhd8ed1ab_0    conda-forge
icu                       73.2                 h59595ed_0    conda-forge
idna                      3.10               pyhd8ed1ab_0    conda-forge
imageio                   2.35.1                   pypi_0    pypi
importlib-metadata        8.5.0                    pypi_0    pypi
intel-openmp              2023.1.0         hdb19cb5_46306  
jinja2                    3.1.4                    pypi_0    pypi
joblib                    1.4.2                    pypi_0    pypi
jpeg                      9e                   h0b41bf4_3    conda-forge
keyutils                  1.6.1                h166bdaf_0    conda-forge
kiwisolver                1.4.7                    pypi_0    pypi
kornia                    0.5.1                    pypi_0    pypi
krb5                      1.21.3               h659f571_0    conda-forge
lame                      3.100             h166bdaf_1003    conda-forge
lazy-loader               0.4                      pypi_0    pypi
lcms2                     2.15                 hfd0df8a_0    conda-forge
ld_impl_linux-64          2.40                 h12ee557_0  
lerc                      4.0.0                h27087fc_0    conda-forge
libblas                   3.9.0           1_h86c2bf4_netlib    conda-forge
libcblas                  3.9.0           7_ha36c22a_netlib    conda-forge
libcublas                 11.10.3.66                    0    nvidia
libcufft                  10.7.2.124           h4fbf590_0    nvidia
libcufile                 1.11.1.6                      0    nvidia
libcurand                 10.3.7.77                     0    nvidia
libcurl                   8.8.0                hca28451_1    conda-forge
libcusolver               11.4.0.1                      0    nvidia
libcusparse               11.7.4.91                     0    nvidia
libdeflate                1.17                 h0b41bf4_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 hd590300_2    conda-forge
libexpat                  2.6.3                h5888daf_0    conda-forge
libffi                    3.4.4                h6a678d5_1  
libgcc                    14.1.0               h77fa898_1    conda-forge
libgcc-ng                 14.1.0               h69a702a_1    conda-forge
libgfortran               14.1.0               h69a702a_1    conda-forge
libgfortran-ng            14.1.0               h69a702a_1    conda-forge
libgfortran5              14.1.0               hc5f4f2c_1    conda-forge
libgomp                   14.1.0               h77fa898_1    conda-forge
libhwloc                  2.11.1          default_hecaa2ac_1000    conda-forge
libiconv                  1.17                 hd590300_2    conda-forge
liblapack                 3.9.0           7_ha36c22a_netlib    conda-forge
libnghttp2                1.58.0               h47da74e_1    conda-forge
libnpp                    11.7.4.75                     0    nvidia
libnvjpeg                 11.8.0.2                      0    nvidia
libpng                    1.6.43               h2797004_0    conda-forge
librosa                   0.9.2                    pypi_0    pypi
libssh2                   1.11.0               h0841786_0    conda-forge
libstdcxx                 14.1.0               hc0a3c3a_1    conda-forge
libstdcxx-ng              14.1.0               h4852527_1    conda-forge
libtiff                   4.5.0                h6adf6a1_2    conda-forge
libuuid                   1.41.5               h5eee18b_0  
libuv                     1.49.0               hb9d3cd8_0    conda-forge
libwebp-base              1.4.0                hd590300_0    conda-forge
libxcb                    1.13              h7f98852_1004    conda-forge
libxml2                   2.12.7               hc051c1a_1    conda-forge
libzlib                   1.2.13               h4ab18f5_6    conda-forge
llvmlite                  0.43.0                   pypi_0    pypi
lmdb                      1.5.1                    pypi_0    pypi
markdown                  3.7                      pypi_0    pypi
markdown-it-py            3.0.0                    pypi_0    pypi
markupsafe                2.1.5                    pypi_0    pypi
matplotlib                3.9.2                    pypi_0    pypi
mdurl                     0.1.2                    pypi_0    pypi
mkl                       2023.1.0         h213fc3f_46344  
mpmath                    1.3.0                    pypi_0    pypi
ncurses                   6.4                  h6a678d5_0  
nettle                    3.6                  he412f7d_0    conda-forge
networkx                  3.3                      pypi_0    pypi
ninja                     1.10.2.3                 pypi_0    pypi
numba                     0.60.0                   pypi_0    pypi
numpy                     1.23.4                   pypi_0    pypi
nvidia-cublas-cu12        12.1.3.1                 pypi_0    pypi
nvidia-cuda-cupti-cu12    12.1.105                 pypi_0    pypi
nvidia-cuda-nvrtc-cu12    12.1.105                 pypi_0    pypi
nvidia-cuda-runtime-cu12  12.1.105                 pypi_0    pypi
nvidia-cudnn-cu12         9.1.0.70                 pypi_0    pypi
nvidia-cufft-cu12         11.0.2.54                pypi_0    pypi
nvidia-curand-cu12        10.3.2.106               pypi_0    pypi
nvidia-cusolver-cu12      11.4.5.107               pypi_0    pypi
nvidia-cusparse-cu12      12.1.0.106               pypi_0    pypi
nvidia-nccl-cu12          2.20.5                   pypi_0    pypi
nvidia-nvjitlink-cu12     12.6.77                  pypi_0    pypi
nvidia-nvtx-cu12          12.1.105                 pypi_0    pypi
opencv-python             4.10.0.84                pypi_0    pypi
openh264                  2.1.1                h780b84a_0    conda-forge
openjpeg                  2.5.0                hfec8fc6_2    conda-forge
openssl                   3.3.2                hb9d3cd8_0    conda-forge
orjson                    3.10.7                   pypi_0    pypi
packaging                 24.1                     pypi_0    pypi
pandas                    2.2.3                    pypi_0    pypi
pillow                    10.4.0                   pypi_0    pypi
pip                       24.2            py310h06a4308_0  
platformdirs              4.3.6                    pypi_0    pypi
pooch                     1.8.2                    pypi_0    pypi
protobuf                  5.28.2                   pypi_0    pypi
pthread-stubs             0.4               hb9d3cd8_1002    conda-forge
pycparser                 2.22               pyhd8ed1ab_0    conda-forge
pydantic                  2.9.2                    pypi_0    pypi
pydantic-core             2.23.4                   pypi_0    pypi
pydub                     0.25.1                   pypi_0    pypi
pygments                  2.18.0                   pypi_0    pypi
pyparsing                 3.1.4                    pypi_0    pypi
pysocks                   1.7.1              pyha2e5f31_6    conda-forge
python                    3.10.15              he870216_1  
python-dateutil           2.9.0.post0              pypi_0    pypi
python-multipart          0.0.12                   pypi_0    pypi
python_abi                3.10                    2_cp310    conda-forge
pytorch                   1.13.1          py3.10_cuda11.7_cudnn8.5.0_0    pytorch
pytorch-cuda              11.7                 h778d358_5    pytorch
pytorch-mutex             1.0                        cuda    pytorch
pytz                      2024.2                   pypi_0    pypi
pyyaml                    6.0.2                    pypi_0    pypi
readline                  8.2                  h5eee18b_0  
requests                  2.32.3             pyhd8ed1ab_0    conda-forge
resampy                   0.4.3                    pypi_0    pypi
rhash                     1.4.3                hd590300_2    conda-forge
rich                      13.9.2                   pypi_0    pypi
ruff                      0.6.9                    pypi_0    pypi
scikit-image              0.24.0                   pypi_0    pypi
scikit-learn              1.5.2                    pypi_0    pypi
scipy                     1.13.1                   pypi_0    pypi
semantic-version          2.10.0                   pypi_0    pypi
setuptools                75.1.0          py310h06a4308_0  
shellingham               1.5.4                    pypi_0    pypi
six                       1.16.0                   pypi_0    pypi
sniffio                   1.3.1                    pypi_0    pypi
soundfile                 0.12.1                   pypi_0    pypi
sqlite                    3.45.3               h5eee18b_0  
starlette                 0.38.6                   pypi_0    pypi
sympy                     1.13.3                   pypi_0    pypi
tb-nightly                2.19.0a20241009          pypi_0    pypi
tbb                       2021.13.0            h84d6215_0    conda-forge
tensorboard-data-server   0.7.2                    pypi_0    pypi
threadpoolctl             3.5.0                    pypi_0    pypi
tifffile                  2024.9.20                pypi_0    pypi
tk                        8.6.14               h39e8969_0  
tomli                     2.0.2                    pypi_0    pypi
tomlkit                   0.12.0                   pypi_0    pypi
torchaudio                0.13.1              py310_cu117    pytorch
torchvision               0.14.1              py310_cu117    pytorch
tqdm                      4.66.5                   pypi_0    pypi
triton                    3.0.0                    pypi_0    pypi
typer                     0.12.5                   pypi_0    pypi
typing_extensions         4.12.2             pyha770c72_0    conda-forge
tzdata                    2024.2                   pypi_0    pypi
urllib3                   2.2.3              pyhd8ed1ab_0    conda-forge
uvicorn                   0.31.0                   pypi_0    pypi
websockets                12.0                     pypi_0    pypi
werkzeug                  3.0.4                    pypi_0    pypi
wheel                     0.44.0          py310h06a4308_0  
xorg-libxau               1.0.11               hb9d3cd8_1    conda-forge
xorg-libxdmcp             1.1.5                hb9d3cd8_0    conda-forge
xz                        5.4.6                h5eee18b_1  
yapf                      0.40.2                   pypi_0    pypi
zipp                      3.20.2                   pypi_0    pypi
zlib                      1.2.13               h4ab18f5_6    conda-forge
zstandard                 0.23.0          py310ha39cb0e_1    conda-forge
zstd                      1.5.6                ha6fb4c9_0    conda-forge

```

Pip package versions:
```
(retalker) imv@srv-10g:~/code/msm/retalker/retalker$ pip list
Package                  Version
------------------------ ---------------
absl-py                  2.1.0
addict                   2.4.0
aiofiles                 23.2.1
annotated-types          0.7.0
anyio                    4.6.0
audioread                3.0.1
basicsr                  1.4.2
Brotli                   1.1.0
certifi                  2024.8.30
cffi                     1.17.1
charset-normalizer       3.4.0
click                    8.1.7
contourpy                1.3.0
cycler                   0.12.1
decorator                5.1.1
dlib                     19.24.0
einops                   0.4.1
exceptiongroup           1.2.2
face_alignment           1.3.4
facexlib                 0.2.5
fastapi                  0.115.0
ffmpy                    0.4.0
filelock                 3.16.1
filterpy                 1.4.5
fonttools                4.54.1
fsspec                   2024.9.0
future                   1.0.0
gradio                   5.0.0
gradio_client            1.4.0
grpcio                   1.66.2
h11                      0.14.0
h2                       4.1.0
hpack                    4.0.0
httpcore                 1.0.6
httpx                    0.27.2
huggingface-hub          0.25.2
hyperframe               6.0.1
idna                     3.10
imageio                  2.35.1
importlib_metadata       8.5.0
Jinja2                   3.1.4
joblib                   1.4.2
kiwisolver               1.4.7
kornia                   0.5.1
lazy_loader              0.4
librosa                  0.9.2
llvmlite                 0.43.0
lmdb                     1.5.1
Markdown                 3.7
markdown-it-py           3.0.0
MarkupSafe               2.1.5
matplotlib               3.9.2
mdurl                    0.1.2
mpmath                   1.3.0
networkx                 3.3
ninja                    1.10.2.3
numba                    0.60.0
numpy                    1.23.4
nvidia-cublas-cu12       12.1.3.1
nvidia-cuda-cupti-cu12   12.1.105
nvidia-cuda-nvrtc-cu12   12.1.105
nvidia-cuda-runtime-cu12 12.1.105
nvidia-cudnn-cu12        9.1.0.70
nvidia-cufft-cu12        11.0.2.54
nvidia-curand-cu12       10.3.2.106
nvidia-cusolver-cu12     11.4.5.107
nvidia-cusparse-cu12     12.1.0.106
nvidia-nccl-cu12         2.20.5
nvidia-nvjitlink-cu12    12.6.77
nvidia-nvtx-cu12         12.1.105
opencv-python            4.10.0.84
orjson                   3.10.7
packaging                24.1
pandas                   2.2.3
Pillow                   9.4.0
pip                      24.2
platformdirs             4.3.6
pooch                    1.8.2
protobuf                 5.28.2
pycparser                2.22
pydantic                 2.9.2
pydantic_core            2.23.4
pydub                    0.25.1
Pygments                 2.18.0
pyparsing                3.1.4
PySocks                  1.7.1
python-dateutil          2.9.0.post0
python-multipart         0.0.12
pytz                     2024.2
PyYAML                   6.0.2
requests                 2.32.3
resampy                  0.4.3
rich                     13.9.2
ruff                     0.6.9
scikit-image             0.24.0
scikit-learn             1.5.2
scipy                    1.13.1
semantic-version         2.10.0
setuptools               75.1.0
shellingham              1.5.4
six                      1.16.0
sniffio                  1.3.1
soundfile                0.12.1
starlette                0.38.6
sympy                    1.13.3
tb-nightly               2.19.0a20241009
tensorboard-data-server  0.7.2
threadpoolctl            3.5.0
tifffile                 2024.9.20
tomli                    2.0.2
tomlkit                  0.12.0
torch                    1.13.1
torchaudio               0.13.1
torchvision              0.14.1
tqdm                     4.66.5
triton                   3.0.0
typer                    0.12.5
typing_extensions        4.12.2
tzdata                   2024.2
urllib3                  2.2.3
uvicorn                  0.31.0
websockets               12.0
Werkzeug                 3.0.4
wheel                    0.44.0
yapf                     0.40.2
zipp                     3.20.2
zstandard                0.23.0

```

**Comment by iv2985** [comment]
Update: this was fixed with downgrading numpy as described in other comments.
`conda install numpy=1.23.1`
